In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
from nhdp_vi import NHDP, prep_data

In [3]:
np.random.seed(1)

In [4]:
vocab = ['a', 'b', 'c', 'd', 'e']
docs = ['a b c d e']
for i in range(20):
    doc = ' '.join(np.random.choice(vocab, size=10))
    docs.append(doc)
vocab, data = prep_data(docs)

In [5]:
print vocab
print data.todense()

['a', 'b', 'c', 'd', 'e']
[[1 1 1 1 1]
 [3 2 0 2 3]
 [0 1 4 1 4]
 [2 6 0 0 2]
 [3 4 1 2 0]
 [2 1 1 3 3]
 [2 4 3 0 1]
 [2 2 2 3 1]
 [4 2 1 2 1]
 [1 0 1 4 4]
 [2 2 2 0 4]
 [2 3 1 0 4]
 [2 1 4 1 2]
 [2 3 4 0 1]
 [3 4 1 1 1]
 [2 2 1 3 2]
 [4 2 1 1 2]
 [1 1 2 4 2]
 [5 0 2 1 2]
 [2 2 2 1 3]
 [0 0 1 7 2]]


In [6]:
nhdp_obj = NHDP()
#nhdp_obj.inference(data)

In [7]:
#len(nhdp_obj.history)

In [8]:
#nhdp_obj.history["a", np.index_exp[-10:]]

In [9]:
from paisley_to_python import nHDP_init, main_loop

In [10]:
tree = nHDP_init(data, num_topics=[5,5,5], scale=100)
tree

[{'beta_cnt': array([ 28.17172528,  19.40614346,  16.02110842,  10.55774588,  25.84327695]),
  'cnt': 42.857142857142854,
  'me': array([0, 0]),
  'parent': array([0])},
 {'beta_cnt': array([ 14.11686786,  12.05331797,  17.95706806,  29.41227028,  26.46047583]),
  'cnt': 28.571428571428573,
  'me': array([0, 1]),
  'parent': array([0])},
 {'beta_cnt': array([ 24.24004438,  37.15945339,  22.82362409,   8.11579722,   7.66108091]),
  'cnt': 19.047619047619047,
  'me': array([0, 2]),
  'parent': array([0])},
 {'beta_cnt': array([ 20.1424267 ,  57.00298045,   1.4255442 ,   2.16755453,  19.26149412]),
  'cnt': 4.7619047619047619,
  'me': array([0, 3]),
  'parent': array([0])},
 {'beta_cnt': array([  0.17551713,   0.33932599,   9.9904923 ,  69.4262844 ,  20.06838018]),
  'cnt': 4.7619047619047619,
  'me': array([0, 4]),
  'parent': array([0])},
 {'beta_cnt': array([  0.77748866,  10.8982235 ,  48.28859005,   2.18973812,  37.84595967]),
  'cnt': 14.285714285714286,
  'me': array([0, 0, 0]),
  

In [11]:
from collections import Counter

In [12]:
ccc = Counter([len(t["me"]) for t in tree])
print sum(ccc.values())

105


In [13]:
print "========"
print '\n'.join(["{} -> {}".format(t["me"], t["beta_cnt"]) for t in tree])
print "========"
print '\n'.join(["{} -> {}".format(t["me"], t["cnt"]) for t in tree])
print "========"
print '\n'.join(["{} -> {}".format(t["me"], t["parent"]) for t in tree])

[0 0] -> [ 28.17172528  19.40614346  16.02110842  10.55774588  25.84327695]
[0 1] -> [ 14.11686786  12.05331797  17.95706806  29.41227028  26.46047583]
[0 2] -> [ 24.24004438  37.15945339  22.82362409   8.11579722   7.66108091]
[0 3] -> [ 20.1424267   57.00298045   1.4255442    2.16755453  19.26149412]
[0 4] -> [  0.17551713   0.33932599   9.9904923   69.4262844   20.06838018]
[0 0 0] -> [  0.77748866  10.8982235   48.28859005   2.18973812  37.84595967]
[0 0 1] -> [  3.94254346  14.38629954  13.1966687   55.26944091  13.20504739]
[0 0 2] -> [ 82.27462908   8.28838078   7.41218068   0.56120806   1.4636014 ]
[0 0 3] -> [  1.77685591  44.04431944   1.29938036   0.51699528  52.36244901]
[0 0 4] -> [ 47.62864675  10.01626297   2.18414095  38.84631367   1.32463567]
[0 1 0] -> [ 40.95465006  50.96642745   6.97217226   0.08430112   1.02244911]
[0 1 1] -> [  2.39189641   0.61000155  13.75224946  83.00347274   0.24237983]
[0 1 2] -> [  0.77778783   0.50100966  60.72609962   0.6312211   37.363881

In [14]:
np.random.seed(1)

In [15]:
data[0,:].indices

array([4, 1, 2, 3, 0], dtype=int32)

In [16]:
main_loop(data, num_topics=[5,5,5], scale=100000)

B_up                 : <type 'numpy.ndarray'>                             shape = (115, 5)    
C_act                : <type 'numpy.ndarray'>                             shape = (10, 4)     
D                    : <type 'int'>                                       = 21                
Eln1_V               : <type 'numpy.float64'>                             = -1.0              
ElnB                 : <type 'numpy.ndarray'>                             shape = (115, 5)    
ElnB_d               : <type 'numpy.ndarray'>                             shape = (115, 4)    
ElnP_d               : <type 'numpy.ndarray'>                             shape = (115,)      
ElnPtop              : <type 'numpy.ndarray'>                             shape = (115,)      
ElnPtop_act          : <type 'numpy.ndarray'>                             shape = (10,)       
ElnV                 : <type 'numpy.float64'>                             = -1.0              
H                    : <type 'numpy.ndarray'>     

ValueError: operands could not be broadcast together with shapes (115,) (4,) 

In [ ]:
from paisley_to_python import process_tree

In [ ]:
res = process_tree(tree, beta0=1.0, gamma1=1.0)

In [ ]:
import sympy as sp

In [ ]:
def log_godel_to_seq(g):
    ints = np.exp(np.atleast_1d(g)).round().astype('int')
    result = []
    for i in ints:
        f = sorted(sp.factorint(i).items(), key=lambda x: x[0])
        result.append(np.array([fi[1] for fi in f]) - 1)
    return result

In [ ]:
for a, b in zip(log_godel_to_seq(res[2]), log_godel_to_seq(res[3])):
    assert np.array_equal(b[:-1], a)
    print a, b